services:
  traceability:
    build: .
    image: energous_vi
    container_name: energous_vi
    ports:
      - "5051:5051"
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=production